#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")
if [ "$files" = "" ]; then
    exit 0
fi

pass=true

echo "\nValidating ES6:\n"

for file in ${files}; do
    result=$(node_modules/eslint/bin/eslint.js ${file})
    if [ "$result" == "" ]; then
        echo "\t\033[32mESLint Passed: ${file}\033[0m"
    else
        echo "\t\033[31mESLint Failed: ${file}\033[0m"
        echo "$result"
        pass=false
    fi
done

echo "\ES6 validation complete\n"

if ! $pass; then
    echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESHint but do not. Please fix the ESLint-ES6 errors and try again.\n"
    exit 1
else
    echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi
